apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - helmrelease.yaml
  - chart-gitrepository.yaml
  - monitoring.yaml

namespace: ethereum

labels:
  - pairs:
      app: ethereum-node
      component: blockchain-infrastruscture

commonAnnotations:
  documentation: "https://github.com/gfournierPro/ethereum-infrastructure"
  maintained-by: "gabiwax@gabiwax.com"